CATEGORIES_STANDARD = [0, 22, 43, 44]
CATEGORIES_HIGH = [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 17, 18, 19, 24]
CATEGORIES_LOW = [1, 13]
CATEGORIES_DISC = [20, 21, 23, 24, 32, 34, 38, 42]

CATEGORIES_PERMED = CATEGORIES_HIGH + CATEGORIES_LOW + [19, 41]

CATEGORIES_UNUSED = [2, 19]

CATEGORIES_SHAMAN = [4, 8]
CATEGORIES_BOOTCAMP = [3, 13]
CATEGORIES_SURVIVOR = [10, 11, 24]

CATEGORIES_TAG = CATEGORIES_HIGH + [41]

CATEGORIES_MAP = {
    "h": CATEGORIES_HIGH,
    "high": CATEGORIES_HIGH,

    "l": CATEGORIES_LOW,
    "low": CATEGORIES_LOW,

    "p": CATEGORIES_PERMED,
    "perm": CATEGORIES_PERMED,
    "permanent": CATEGORIES_PERMED,

    "d": CATEGORIES_DISC,
    "disc": CATEGORIES_DISC,
    "discussion": CATEGORIES_DISC,

    "s": CATEGORIES_STANDARD,
    "standard": CATEGORIES_STANDARD,

    "u": CATEGORIES_UNUSED,
    "unused": CATEGORIES_UNUSED,
}