# Generated by Django 5.2.4 on 2025-08-10 23:06

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from pgvector.django import VectorExtension
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        TrigramExtension(),
        VectorExtension(),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'author',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['name'], name='author_name_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.PositiveSmallIntegerField(db_index=True)),
                ('xml', models.TextField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=128)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='maps.author')),
            ],
            options={
                'db_table': 'map',
                'indexes': [models.Index(fields=['category'], name='map_category_idx'), models.Index(fields=['author'], name='map_author_idx'), models.Index(fields=['category', 'author'], name='map_category_author_idx'), django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='map_tags_gin'), django.contrib.postgres.indexes.GinIndex(fields=['xml'], name='map_xml_trgm', opclasses=['gin_trgm_ops']), pgvector.django.indexes.IvfflatIndex(fields=['embedding'], lists=100, name='map_emb_ivf', opclasses=['vector_l2_ops'])],
            },
        ),
    ]
