# Generated by Django 5.2.4 on 2025-07-31 01:27

import django.contrib.postgres.indexes
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        TrigramExtension(),
        VectorExtension(),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mapcount', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('xml', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=96)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='maps.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='maps.category')),
            ],
            options={
                'db_table': 'map',
                'indexes': [models.Index(fields=['author'], name='map_author__b3f510_idx'), models.Index(fields=['category'], name='map_categor_05af96_idx'), django.contrib.postgres.indexes.GinIndex(fields=['xml'], name='map_xml_trgm', opclasses=['gin_trgm_ops']), pgvector.django.indexes.IvfflatIndex(fields=['embedding'], lists=100, name='map_emb_ivf', opclasses=['vector_l2_ops'])],
            },
        ),
    ]
