# Generated by Django 5.2.4 on 2025-08-16 19:38

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorCategoryCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(db_index=True)),
                ('map_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'author_category_counter',
            },
        ),
        migrations.CreateModel(
            name='AuthorTagCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=64)),
                ('map_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'author_tag_counter',
            },
        ),
        migrations.RemoveIndex(
            model_name='map',
            name='map_category_author_idx',
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='authorcategorycounter',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_counters', to='maps.author'),
        ),
        migrations.AddField(
            model_name='authortagcounter',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_counters', to='maps.author'),
        ),
        migrations.AddIndex(
            model_name='authorcategorycounter',
            index=models.Index(fields=['category', 'map_count'], name='acc_category_count_idx'),
        ),
        migrations.AddIndex(
            model_name='authorcategorycounter',
            index=models.Index(fields=['author'], name='acc_author_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='authorcategorycounter',
            unique_together={('author', 'category')},
        ),
        migrations.AddIndex(
            model_name='authortagcounter',
            index=models.Index(fields=['tag', 'map_count'], name='atc_tag_count_idx'),
        ),
        migrations.AddIndex(
            model_name='authortagcounter',
            index=models.Index(fields=['author'], name='atc_author_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='authortagcounter',
            unique_together={('author', 'tag')},
        ),
    ]
